quintoandar/butterfree

README.md
The current hyperlink on README.md leads to a restricted version. 
This PR replaces the current hyperlink to the public version.
Previous hyperlink requires restricted access
The fixed version works as expected
=> Fixes docs hyperlink on README

CHANGELOG.md, setup.py
Release 1.0.0
* Add license ([#185](https://github.com/quintoandar/butterfree/pull/185))
* [MLOP-386] Create PR Guideline on CONTRIBUTING.md ([#190](https://github.com/quintoandar/butterfree/pull/190))
* [MLOP-390] Create method to get feature sets' description ([#188](https://github.com/quintoandar/butterfree/pull/188)) 
* [MLOP-376] Change spark version on Butterfree ([#177](https://github.com/quintoandar/butterfree/pull/177))
* [MLOP-344] Update README with documentation ([#175](https://github.com/quintoandar/butterfree/pull/175))
* [MLOP-375] Refactor Sink and OnlineFeatureStore write to entity flow ([#182](https://github.com/quintoandar/butterfree/pull/182))
* [MLOP-363] DB Credentials Setup Refactor ([#187](https://github.com/quintoandar/butterfree/pull/187))
* [MLOP-404] …
=> Release Butterfree to version 1.0.0

README.md, setup.py
We should start using a consistent motto when referring to the library
Adds our motto to the top of README and to the package description
=> Adding the library motto to readme and python package

butterfree/transform/transformations/__init__.py, tests/integration/butterfree/transform/test_aggregated_feature_set.py, tests/unit/butterfree/transform/transformations/test_h3_transform.py
Placing the h3_transform in the __init__ of the transform makes the use of Butterfree always need the h3 lib, so we are removing it from the __init__.
- Imports.
=> Fix H3 import

butterfree/transform/transformations/aggregated_transform.py, tests/unit/butterfree/transform/transformations/test_aggregated_transform.py
Raising a more meaningful exception when an anonymous function is passed to an AggregatedTransform
When passing an anonymous function to an AggregatedTransform an obscure exception was being thrown due to a bug.
I chose to still raise an exception because if we start to support anonymous functions on aggregated transform there would be no easy way to disambiguate between them. It's better to enforce that only named functions are supported and maintain a pattern when constructing feature names. If it's desired in the future we can add support to customizing Names via a property on the Function so we don't always infer based on __name__
Added a Unit test for the new exception
=> Fixing an attribute reference error

butterfree/clients/abstract_client.py, butterfree/clients/cassandra_client.py, butterfree/clients/spark_client.py, requirements.dev.txt, requirements.txt, setup.cfg, tests/unit/butterfree/clients/conftest.py, tests/unit/butterfree/clients/test_cassandra_client.py, tests/unit/butterfree/clients/test_spark_client.py
Fixes type hints for `clients` module
I've introduced `mypy`, `pyspark-stubs` and `typing_extesions` as a dependecies.
All *Type Hint* was fixed in `clients` module (lib and tests).
* `AbstractClient` was transformed in a **GenericType**
* Fixed types in `SparkClient` and `CassandraClient`
* `CassandraColumn` type was created
* `clients` tests were typed too
Mypy check:
```sh
mypy butterfree/clients
```
I didn't include the `mypy` to `donre` check because we have to fixes the other modules, to prevent the falling build for a long time!
refs #195
=> Fixes type hints for `clients` module

.github/workflows/publish.yml, .github/workflows/test.yml, CONTRIBUTING.md, Makefile, README.md, docs/requirements.txt, docs/source/getstart.md, requirements.dev.txt, requirements.lint.txt, requirements.txt, setup.py
We use some typing features from Python 3.7 and our environment uses this version too. In Python 3.6 images some typing features were not working properly.
- New docker image for the CI using Python 3.7
- Removing unused dependencies/imports
- Adjusting references to Python Version
Unit/Integration tests
=> [MLOP-440] Python 3.7 bump and Fixing Dependencies

.github/workflows/publish.yml
Container's name was wrong in Publish.yml file.
- Workflow
=> Fix container name in Workflow

butterfree/extract/source.py, butterfree/pipelines/feature_set_pipeline.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/unit/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/transform/test_aggregated_feature_set.py, tests/unit/butterfree/transform/test_feature_set.py
The feature set pipeline will receive a start_date parameter, so we can implement interval processing in Butterfree.
Added an optional ```start_date``` parameter to the run method within the scope of the ```FeatureSetPipeline``` class.
Unit tests.
I've also added some methods inside FeatureSet and AggregatedFeatureSet classes to retrieve the proper start_date. For a feature set, it's simply the same start date, however for an aggregated feature set, we should take the time window into account (the logic itself will be implemented later).
=> [MLOP-398] Pipeline run method will receive an optional start_date argument #212

butterfree/constants/window_definitions.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/utils/window_spec.py, tests/unit/butterfree/transform/test_aggregated_feature_set.py
The Source class must be filtered according to the feature set definition.
Added a method in AggregatedFeatureSet to obtain the correct starting data for computing the transformations.
Unit tests
=> [MLOP-399] Source date boundaries must be changed

butterfree/configs/environment.py, butterfree/extract/readers/__init__.py, butterfree/extract/readers/incremental_strategy.py, butterfree/extract/readers/reader.py, tests/unit/butterfree/extract/conftest.py, tests/unit/butterfree/extract/readers/test_incremental_strategy.py, tests/unit/butterfree/extract/readers/test_reader.py
In a incremental run the readers need to be filtered based on an incremental strategy.
- New filter in readers build
- New `IncrementalStrategy` entity
- New tests for `Reader` and `IncrementalStrategy`
locally with tests
Depend on this PR: https://github.com/quintoandar/butterfree/pull/220
=> [MLOP-400] Readers Incremental Strategy

.github/workflows/test.yml, Makefile, butterfree/clients/spark_client.py, butterfree/constants/columns.py, butterfree/constants/data_type.py, butterfree/constants/spark_constants.py
Fixes type hints for `constants` module
All *Type Hint* was fixed in `constants` module.
Mypy check:
```sh
mypy butterfree/constants
```
I have added type check to the workflow, but just only for the modules where we fixed the type hints!
refs #195
=> Fixes type hints for `constants` module

Makefile
```make environment``` command was not running, so this a fix.
Homebrew Pyenv has not provided a ```3.7.7``` version, therefore it was downgraded to ```3.7.6```. 
Locally.
=> [FIX] Downgrade Python Version in Pyenv

docs/requirements.txt
Some modules of our documentation are blank.
- Docs Requirements
It is possible that more errors will appear after fixing this error.
=> Fix Docs - Add more dependencies

butterfree/clients/spark_client.py, tests/unit/butterfree/clients/conftest.py, tests/unit/butterfree/clients/test_spark_client.py
After writing only the daily dataset we need a way to add the daily partitions to Spark's metastore.
New method `add_table_partitions` on `SparkClient`
Locally and in this notebook: https://dbc-eea99378-83b2.cloud.databricks.com/?o=3542631183402105#notebook/403249991677936/command/2139563602263960
I didn't create a new entity to hold key-value data from partitions because someone can use the method to add partitions from any column, not just year/month/day. So maybe in this case, for initial implementation, a generalist data structure like a list of dicts can handle this problem well. I think the Docstring that I've written shows an example and it's clear to the user how he is supposed to use this method. But I'm open to ideas :rocket: :rocket: :rocket:
=> [MLOP-405] Spark Client Add Partitions Method

butterfree/dataframe_service/__init__.py, butterfree/dataframe_service/incremental_strategy.py, butterfree/extract/readers/__init__.py, butterfree/extract/readers/reader.py, butterfree/pipelines/feature_set_pipeline.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/integration/butterfree/transform/conftest.py, tests/integration/butterfree/transform/test_aggregated_feature_set.py, tests/unit/butterfree/dataframe_service/test_incremental_strategy.py, tests/unit/butterfree/extract/readers/test_reader.py
We defined date boundaries within the scope of the transformation layer.
Added methods to enable data filtering.
Unit and Integration tests.
=> [MLOP-401] Define date boundaries within the scope of the writing operation

butterfree/dataframe_service/__init__.py, butterfree/dataframe_service/partitioning.py, tests/unit/butterfree/dataframe_service/conftest.py, tests/unit/butterfree/dataframe_service/test_partitioning.py
For the incremental feature, we need to add the partitions after the load. Having a method to extract automatically these partition values from the dataframe will help.
- New method on `dataframe_service` -> `extract_partition_values`
locally with tests.
=> [MLOP-456] Extract Partition Values

butterfree/hooks/__init__.py, butterfree/hooks/hook.py, butterfree/hooks/schema_compatibility/__init__.py, butterfree/hooks/schema_compatibility/spark_table_schema_compatibility_hook.py, tests/unit/butterfree/hooks/schema_compatibility/test_spark_table_schema_compatibility_hook.py
We need a hook to verify the schema compatibility before write to the historical feature store.
- New `Hook` abstract class
- New `SparkTableSchemaCompatibilityHook`
Locally with tests
=> [MLOP-455] Spark Table Schema Compatibility Hook

butterfree/dataframe_service/incremental_strategy.py, butterfree/extract/source.py, butterfree/pipelines/feature_set_pipeline.py, tests/integration/butterfree/pipelines/conftest.py, tests/integration/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/dataframe_service/test_incremental_strategy.py
It was necessary to deal with the ```execution_date``` parameter.
Added a new method within ```FeatureSetPipeline``` class.
Integration tests.
=> [MLOP-436] Deal with execution_date parameter

examples/README.md
This PR is created to fix the third notebook's broken URL in the examples README.
This PR modifies the examples README in order to remove an unnecessary space character in the third notebook's URL.
Tested the third notebook's URL after modifying the README: it points to the correct notebook.
None.
=> Fix broken notebook URL

butterfree/hooks/__init__.py, butterfree/hooks/hookable_component.py, tests/unit/butterfree/hooks/test_hookable_component.py
We need an entity defining with methods to add pre_hook and post_hook functions. Our main modules that will be able to use Hook will just need to inherit from this entity.
- New `HookableComponent` entity
locally with tests
=> [MLOP-459] Create HookableComponent

butterfree/hooks/schema_compatibility/__init__.py, butterfree/hooks/schema_compatibility/cassandra_table_schema_compatibility_hook.py, tests/unit/butterfree/hooks/schema_compatibility/test_cassandra_table_schema_compatibility_hook.py
We want to separate some responsibilities from the main ETL modules (Source, Feature Set, and Sink), so we will create hooks containing these logics.
In this approach, this task is summarized in the creation of a hook where we will have a schema check of the feature sets that will use CassandraClient. This hook will be a pre-writer.
- CassandraTableSchemaCompatibilityHook :star2: 
- Unit Tests
=> [MLOP-454] Create Cassandra Check Hook

butterfree/extract/source.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/unit/butterfree/extract/test_source.py, tests/unit/butterfree/transform/test_feature_set.py
Lazy evaluation in Spark means that the execution will not start until an action, such as count or cache, is triggered. We want to remove them since we’ll have a pre-hook in Writer to check schemas.
- Source
- Feature Set
- Aggregated Feature Set
=> [MLOP-463] Remove transformations from Source and Feature Set

butterfree/load/writers/historical_feature_store_writer.py, tests/integration/butterfree/load/test_sink.py, tests/integration/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/load/conftest.py, tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
We change the way of writing the Historical Feature Store Writer and also change the data partition insertion type.
- HistoricalFSWriter with incremental mode
- Unit tests
=> [MLOP-472] Enable dynamic partition on incremental mode

.gitignore, butterfree/load/writers/historical_feature_store_writer.py, butterfree/load/writers/online_feature_store_writer.py, butterfree/load/writers/writer.py, tests/integration/butterfree/load/test_sink.py, tests/integration/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
The new argument on writers with a default set to True so we can maintain the same Butterfree functionality before the "Incremental Epic" release. This will be a temporary flag that will enable the "Feature toggle".
- HistoricalFSWriter
- Unit and integration tests
=> [MLOP-534] Enable interval and full writing on writers

butterfree/load/writers/online_feature_store_writer.py
Currently, we do not guarantee if your data is the newest one when writing in the online feature store. This happens because we perform full loads. However, even for incremental loads, we're not going to perform any checks for now (well fix this behavior soon).
Update docstring within the scope of the Online Writer explaining the current situation.
=> [MLOP-540] Update Docstrings on OnlineFeatureStoreWriter regarding using end_date parameter

butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/integration/butterfree/transform/conftest.py, tests/integration/butterfree/transform/test_feature_set.py
Added a time filtering method inside ```FeatureSet```.
Added a time filtering method inside ```FeatureSet```.
Integration tests.
=> [MLOP-538] Slice df between start_date and end_date at the output of the FeatureSet

butterfree/clients/spark_client.py, butterfree/configs/db/s3_config.py, butterfree/extract/readers/file_reader.py, butterfree/load/writers/historical_feature_store_writer.py, tests/integration/butterfree/load/test_sink.py, tests/integration/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/clients/test_spark_client.py, tests/unit/butterfree/extract/readers/test_file_reader.py, tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py, tests/unit/butterfree/pipelines/conftest.py, tests/unit/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/transform/conftest.py, tests/unit/butterfree/transform/test_aggregated_feature_set.py, tests/unit/butterfree/transform/test_feature_set.py
When overwritten only the interval and not the table the validate functions need to readjust the written partitions and not the whole table.
- SparkClient Read method
- HFSW Validate method
- Unit and integration tests
=> [MLOP-539] Fix validate on HistoricalFeatureStore for interval writing

butterfree/configs/db/__init__.py, butterfree/configs/db/abstract_config.py, butterfree/configs/db/kafka_config.py, butterfree/configs/environment.py, butterfree/load/processing/__init__.py, butterfree/load/processing/json_transform.py, butterfree/load/writers/historical_feature_store_writer.py, butterfree/load/writers/online_feature_store_writer.py, butterfree/load/writers/writer.py, tests/unit/butterfree/configs/db/conftest.py, tests/unit/butterfree/configs/db/test_kafka_config.py, tests/unit/butterfree/load/conftest.py, tests/unit/butterfree/load/processing/conftest.py, tests/unit/butterfree/load/processing/test_json_transform.py, tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py, tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
We'd like to enable Butterfree to write to Kafka topics.
Added a new ```KafkaConfig``` and possibility to define transformations within the ```Writer``` scope.
Unit tests.
=> [MLOP-563] Enable Butterfree to write to Kafka

Makefile
When the black fails during the test workflow in GitHub actions, a wrong informative message was being shown
- change `make black` to `make apply-style` in the message, according to the Makefile.
Via test workflow
=> Fix unit-test message about black

.github/workflows/publish.yml
This PR intends to fix a issue regarding github actions workflow, as it can be seen [here](https://github.com/quintoandar/butterfree/runs/1444438769?check_suite_focus=true).
Updated Butterfree's workflow, due to the following errors messages:
```bash
Error: Unable to process command '::set-env name=version::1.1.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
=> Fix Butterfree's workflow

butterfree/configs/db/kafka_config.py, butterfree/load/writers/online_feature_store_writer.py, tests/unit/butterfree/configs/db/test_kafka_config.py, tests/unit/butterfree/load/writers/test_online_feature_store_writer.py
We'd like to enable our users to select a custom kafka topic name, in order to write to a given Kafka topic.
Added a new parameter, ```kafka_topic```, within ```KafkaConfig```. It's an optional parameter and if the user don't use it, then we'll have Butterfree's default behavior (it'll look for a topic with the following names: ```feature_set.name``` or ```feature_set.entity```).
Unit tests.
=> [MLOP-590] Adapt KafkaConfig to receive a custom topic name

README.md, docs/requirements.txt, docs/source/getstart.md, docs/source/stream.md, requirements.dev.txt
Read the Docs was unable to build the documentation because of the h3 version. I took the opportunity to update the documentation as well.
- README
- Docs
- Requirements
You can see the build [here](https://readthedocs.org/projects/butterfree/builds/12473033/)
=> FIX Read the Docs build.

.github/workflows/publish.yml, .github/workflows/test.yml
Today we are using a docker image on the docker hub straight from another account, and the DE team uploaded this image to QuintoAndar's account. So we need to change the image in the Github Actions pipeline.
- Github Actions pipelines
=> [MLOP-606] Change docker image in Github Actions Pipeline

butterfree/extract/source.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/unit/butterfree/extract/test_source.py, tests/unit/butterfree/transform/test_feature_set.py
It was necessary to add ```cache``` and ```count``` back to Butterfree, since some odd behaviour was observed after their removal.
Added both ```cache``` and ```count``` back.
=> [MLOP-614] Investigate spark actions removal in Butterfree

.github/workflows/staging.yml
The current configuration of the pipeline did not work because it does not change the name of the package to add to PyPI.
- Staging Pipeline
=> [BUG] Fix Staging GithubActions Pipeline

butterfree/transform/features/timestamp_feature.py, tests/unit/butterfree/transform/features/conftest.py, tests/unit/butterfree/transform/features/test_timestamp_feature.py
When creating historical features we want to have something like `(timestamp, entity_id)` as unique values. However if our source has entries in milliseconds, currently butterfree only store the timestamp within a second precision. This means that two entries in our source with same `id` in the same second(but in different millisecond) will have the same `(timestamp, entity_id)`. This PR aims to address this problem.
Keep milliseconds when using 'from_ms' argument in timestamp feature in the `TimestampFeature`.
I added a unit test covering the case that needed to be addressed, and adapted other tests.
=> Keep milliseconds when using 'from_ms' argument in timestamp feature

.github/workflows/staging.yml
We had an error in the staging pipeline and found that the form we defined for the development version is not valid. So, we changed our trigger strategy.
> Many build tools integrate with distributed version control systems like Git and Mercurial in order to add an identifying hash to the version identifier. As hashes cannot be ordered reliably such versions are not permitted in the public version field.
If we need to create a package based on the staging branch we will have to change the version to this <version> .devN pattern. This will generate a pre-release and package in PyPI.
- GithubActions - Staging
=> Change trigger for pipeline staging

Makefile, butterfree/transform/aggregated_feature_set.py, butterfree/transform/utils/window_spec.py, setup.py, tests/unit/butterfree/transform/conftest.py, tests/unit/butterfree/transform/test_aggregated_feature_set.py
We want to be able to run time aggregations with different slide durations.
Add the slide parameter to `with_windows` function. Slide durations different of 1 day won't use the gap-filling technique we've been using to fix the problem of not updating the aggregations when no events happen.
Unit testing aggregations with slide duration smaller than 1 day.
By not applying the same gap-filling technique, we require the client to make sure it is not using an old aggregation result. The problem is that we run a deduplication logic under the hood, not storing rows with unchanged feature values. So, if the aggregation result doesn't, the row won't be saved into the feature store and the users will find older results there. I don't know, exactly, how …
=> Allow slide selection

butterfree/_cli/__init__.py, butterfree/_cli/main.py, butterfree/_cli/migrate.py, requirements.txt, setup.py, tests/mocks/entities/first/__init__.py, tests/mocks/entities/first/first_pipeline.py, tests/mocks/entities/second/deeper/__init__.py, tests/mocks/entities/second/deeper/second_pipeline.py, tests/unit/butterfree/_cli/test_migrate.py
We want users to be able to set up automated migrations for their feature set pipelines with butterfree.
Add a new command-line interface using [Typer](https://typer.tiangolo.com/). The cli has a single command `migrate PATH` that scans for feature set pipeline definitions under the PATH argument, dynamically instantiating them to call a Migration actor with each pipeline object.
_Have you achieved all the acceptance criteria? How?_
_Is there any alternative flow in the testing process that you want to describe?_
- [] I have made corresponding changes to the documentation;
=> [MLOP-640] Create CLI with migrate command

butterfree/clients/spark_client.py, tests/unit/butterfree/clients/test_spark_client.py
In order to properly perform migrations, it was necessary to implement a method to retrieve the schema from a given table from Spark metastore. 
Implement ```get_schema``` method within Spark client.
Unit test.
=> [MLOP-671] Implement get_schema on Spark client

butterfree/load/writers/historical_feature_store_writer.py, setup.py
We need to partition values to use validate for IntervalMode.
- HistoricalWriterFeatureStore
- Unit tests.
=> [BUG] Apply create_partitions to historical validate

butterfree/migrations/database_migration/metastore_migration.py, tests/unit/butterfree/migrations/database_migration/test_metastore_migration.py
It was necessary to add the partition's types regarding Metastore.
Added partition types.
Unit tests.
=> [FIX] Add Partition types for Metastore

butterfree/extract/readers/kafka_reader.py, setup.py, tests/unit/butterfree/extract/readers/test_kafka_reader.py
We forgot to apply the changed behavior of the SparkClient read in the KafkaReader.
- KafkaReader
- Unit tests
=> [BUG] Fix KafkaReader

docs/source/extract.md
The link in Butterfree Docs for Extract Pre-processing methods is wrong.
- Extract Markdown
=> Fix link in Buttefree Doc

butterfree/clients/cassandra_client.py, setup.py, tests/unit/butterfree/clients/test_cassandra_client.py
We noticed that when creating the session for CassandraClient we were not making the connection, so the session did not always exist.
- CassandraClient
- Unit tests and ["Databricks Tests"](https://dbc-931ee6e0-6803.cloud.databricks.com/?o=4531937035440038#notebook/1759065719312531/command/1759065719312565)
=> [BUG] Fix Cassandra Connect Session

butterfree/migrations/database_migration/cassandra_migration.py, butterfree/migrations/database_migration/database_migration.py, butterfree/migrations/database_migration/metastore_migration.py, setup.py, tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py, tests/unit/butterfree/migrations/database_migration/test_metastore_migration.py
When we change the column type in Cassandra, the query can't receive more than one column, that is, we have to make a query for each column that we want to change the type of.
- DatabaseMigration (Cassandra and Metastore)
- Unit Tests.
=> [BUG] Fix migration query

butterfree/migrations/database_migration/cassandra_migration.py, setup.py, tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py
To apply a Cassandra query with alter type, we need to K_TYPE.
- CassandraMigration
- UnitTests
=> Fix migration query: Add K_TYPE.

docs/source/butterfree.clients.rst, docs/source/butterfree.configs.db.rst, docs/source/butterfree.configs.rst, docs/source/butterfree.constants.rst, docs/source/butterfree.dataframe_service.rst, docs/source/butterfree.extract.pre_processing.rst, docs/source/butterfree.extract.readers.rst, docs/source/butterfree.extract.rst, docs/source/butterfree.hooks.rst, docs/source/butterfree.hooks.schema_compatibility.rst, docs/source/butterfree.load.processing.rst, docs/source/butterfree.load.rst, docs/source/butterfree.load.writers.rst, docs/source/butterfree.migrations.database_migration.rst, docs/source/butterfree.migrations.rst, docs/source/butterfree.pipelines.rst, docs/source/butterfree.reports.rst, docs/source/butterfree.rst, docs/source/butterfree.transform.features.rst, docs/source/butterfree.transform.rst, docs/source/butterfree.transform.transformations.rst, docs/source/butterfree.transform.transformations.user_defined_functions.rst, docs/source/butterfree.transform.utils.rst, docs/source/butterfree.validations.rst, docs/source/cli.md, docs/source/home.md, docs/source/index.rst, requirements.dev.txt
After adding the new tool for schema migration, we must add some initial notes about it on our documentation.
- Adding `cli.md` describing more about the new tool.
- Run update-docs created and updated docs that were outdated.
=> MLOP-642 Document migration in Butterfree

butterfree/migrations/database_migration/database_migration.py
Improve logging messages in the migration module.
+ Inform in drone console which features set is doing
- DatabaseMigration
- Unit test and local test.
=> [MLOP-728] Improve logging messages

butterfree/transform/transformations/aggregated_transform.py, setup.py
To not have discrepancies with names in storages (like Cassandra) with CaseSensitive, we apply `str.lower()` to the function name applied in the AggregatedTransform.
- AggregatedTransform
- Unit and integration test
=> [MLOP-729][BUG] Fix method to generate agg feature name

butterfree/load/writers/historical_feature_store_writer.py, setup.py, tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
The writing of the interval mode was just being saving the data in S3, that is, it wasn't taking the data to SparkMetastore.
- HistoticalFSWriter
- Unit tests and Databricks.
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._
=> [MLOP-691]  Include step to add partition to SparkMetastore during writing of Butterfree

examples/simple_feature_set/simple_feature_set.ipynb, examples/spark_function_and_window/spark_function_and_window.ipynb
This PR adds a missing link in the `examples/simple_feature_set/simple_feature_set.ipynb`. The link is referring to H3 Geohash information, currently the link in the markdown is empty and redirects to rendered notebook.
Fixes: #329 
There is only one change being made in this PR and that is addition of a link to H3 Geohash information.
There is no need to test anything, apart from the fact that the link that I have updated is the same link authors refer to. If its one and the same, then there is no need to test anything as there is no code changes.
Reviewers need to verify that the link that I have added is the same link that the author of the notebook intended to add.
=> Add the missing link for H3 geohash

.github/workflows/publish.yml, .github/workflows/staging.yml, .github/workflows/test.yml, requirements.lint.txt, tests/unit/butterfree/configs/db/test_cassandra_config.py
The runner used for executing the Github Actions appears to be outdated and not working.
The step will be stuck finding for a runner:
- updating the runner to `ubuntu-22.04`
Running PR workflows
=> Update Github Actions Workflow runner

docs/requirements.txt
Today the Butterfree documentation uses my account to be hosted on Read the Docs, and the DevOps team created an account for QuintoAndar, so we need to change the management account.
- Delete the Sphinx version.
=> fix(mlop-607) Change butterfree maintainers docs

butterfree/load/sink.py, butterfree/load/writers/writer.py
For some cases there's no need to apply row count validation (e.g. when using DELTA as storage format) and for some other cases this process might not be wanted.
- Add a row count validation flag on Abstract Writer
- Add a check on the Sink to enable row count validation
=> feat: Optional row count validation

butterfree/load/writers/historical_feature_store_writer.py, requirements.dev.txt
- Add missing param on HistoricalFeatureStoreWriter
- Add libs in order to work `make package`
=> fix: add missing parameter, add setup libs

butterfree/extract/source.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py
The `eager_evaluation` param forces Spark to apply the currently mapped changes to a DataFrame. When this parameter is set to False, Spark follows its standard behavior of lazy evaluation. Lazy evaluation can improve Spark's performance as it allows Spark to build the best version of the execution plan.
The `row_deduplication` is not applicable to all scenarios. For instance, when using Delta operations, row deduplication can be done through `merge` operations.
- Add new arguments to enable/disable eager evaluation and row deduplication in Source and FeatureSet classes.
- Databricks notebooks
=> feat(MLOP-1985): optional params

.flake8, butterfree/automated/feature_set_creation.py, setup.cfg, tests/unit/butterfree/automated/test_feature_set_creation.py
- feat(updating-auto-fs-creation): adding methods to the class as private and add Table dataclass
- feat(updating-auto-fs-creation): using dataclass and adding typing
- feat(updating-auto-fs-creation): finish using all type hints and apply format
=> feat(mlop-2145): updating auto fs creation

butterfree/automated/feature_set_creation.py, setup.cfg, tests/unit/butterfree/automated/test_feature_set_creation.py
Allow users to automatically create feature sets readers and features
- A class that extract readers and features from a SQL String and infer data types with a sample DataFrame
=> feat(MLOP-2145): add feature set creation script

butterfree/constants/data_type.py, butterfree/transform/features/timestamp_feature.py, tests/integration/butterfree/pipelines/test_feature_set_pipeline.py, tests/unit/butterfree/transform/features/test_timestamp_feature.py
Turn [no timezone timestamp available](https://community.databricks.com/t5/technical-blog/introducing-timestamp-ntz-in-apache-spark-the-timestamp-without/ba-p/50586). If one use Butterfree with TimestampFeature it can obtain different values of timestamps due to SO configs, which is bad for time-sensitive feature sets.
- New DataType (require Spark >= 3.4)
- Possibility to change TimestampFeature data type
- Tests for timestamp differences
Local tests
=> feat(MLOP-2236): add NTZ

butterfree/configs/db/cassandra_config.py, requirements.txt
Adapt Cassandra Config to the new libs versions that generates values with lower case. Pin numpy as version 2.x was released.
* Cassandra types as lowercase
* Pin numpy version
=> fix: cassandra configs

butterfree/configs/db/cassandra_config.py, tests/unit/butterfree/migrations/database_migration/conftest.py, tests/unit/butterfree/migrations/database_migration/test_cassandra_migration.py
Cassandra migration broke every time because there's a missing whitespace in the keys.
Add whitespace; add tests
=> fix: Cassandra config keys

butterfree/load/writers/historical_feature_store_writer.py, tests/unit/butterfree/transform/conftest.py
Our release failed because Sonar complained about duplicated lines.
=> Fix dup code

butterfree/_cli/migrate.py, butterfree/extract/source.py, butterfree/pipelines/feature_set_pipeline.py, butterfree/transform/aggregated_feature_set.py, butterfree/transform/feature_set.py, tests/unit/butterfree/transform/test_feature_set.py
Improve Butterfree performance.
- Fix migration script (when receiving parameter)
- Use persist instead of caching for source data. Persist allows storage level choice.
- Test partitions before apply repartition on dataframes.
- Persist is the final transformation of extraction. When one persist (or cache) before all the transformations is applied, it may be forcing Spark to persist several times.
=> fix: performance improvements

butterfree/migrations/database_migration/cassandra_migration.py, butterfree/transform/aggregated_feature_set.py
We want the Transform phase to be as fast as possible.
Some Cassandra versions do not allow column type change.
- Remove reduce in column transformations
- Apply incremental filter as soon as possible
- Force dataframe materialization only for small amount of data
Databricks notebook
=> fix: performance adjustments, migrate

Makefile, butterfree/clients/cassandra_client.py, tests/unit/butterfree/clients/test_cassandra_client.py, tests/unit/butterfree/transform/transformations/conftest.py
- Makefile: changes to exclude `venv` files from checks and formatting
- Add `_validate_and_format_cassandra_host` and unit tests 
- `tests/unit/butterfree/transform/transformations/conftest.py`: fixing a test
=> feat(mlop-2456): add protection to host setting on cassandra_client
