README.md

There are some old references in Readme
- Update `Readme.md`

Update Readme for 1.0.0

---

butterfree/reports/metadata.py
butterfree/transform/feature_set.py

We forgot to handle cases of features without transformations.
- Schema
- Reports module
Unit and integration tests.

Fix schema and reports.

---

butterfree/reports/metadata.py
butterfree/transform/feature_set.py

We forgot to handle cases of features without transformations.
- Schema
- Reports module
Unit and integration tests.

Fix reports

---

.github/workflows/publish.yml
WORKFLOW.md

The current workflow will not work as the master branch is protected.
- Publish workflow
- WORKFLOW.md
Integration test

Change workflow.

---

butterfree/transform/transformations/sql_expression_transform.py
setup.cfg
tests/unit/butterfree/transform/transformations/test_sql_expression_transform.py

Fix for the Issue #77 
- Fix on the transformation
- New testing asserting overwriting the column with sql transform
locally with new unit test

Issue #77 Fix

---

butterfree/pipelines/feature_set_pipeline.py

Try to not "break" the original interface, adding the new args to the end.
- FSPipeline

[MLOP-537] Refactor pipeline run interface

---

butterfree/hooks/hookable_component.py
tests/integration/butterfree/pipelines/conftest.py
tests/integration/butterfree/pipelines/test_feature_set_pipeline.py

We need integration tests asserting the main new features from this epic.
- Bugfix on hookable component
- Testing a pipeline with hooks on all modules
- Testing a pipeline running different intervals
locally with tests

[MLOP-484] Epic Incremental Feature Integration Tests

---

CHANGELOG.md
docs/source/butterfree.configs.db.rst
docs/source/butterfree.load.processing.rst
docs/source/butterfree.load.rst
docs/source/configuration.md
setup.py

* [MLOP-563] Enable Butterfree to write to Kafka ([#258](https://github.com/quintoandar/butterfree/pull/258))
* Update README ([#257](https://github.com/quintoandar/butterfree/pull/257))
* [FIX] Downgrade Python Version in Pyenv ([#227](https://github.com/quintoandar/butterfree/pull/227))
* [FIX] Fix docs ([#229](https://github.com/quintoandar/butterfree/pull/229)) 
* [FIX] Fix Docs - Add more dependencies ([#230](https://github.com/quintoandar/butterfree/pull/230))
* Fix broken notebook URL ([#236](https://github.com/quintoandar/butterfree/pull/236)) 
* Issue #77 Fix ([#245](https://github.com/quintoandar/butterfree/pull/245))
[MLOP-563]: https://quintoandar.atlassian.net/browse/MLOP-563

Release 1.1.0

---

CHANGELOG.md
docs/source/configuration.md
setup.py

* [MLOP-590] Adapt KafkaConfig to receive a custom topic name ([#266](https://github.com/quintoandar/butterfree/pull/266))
[MLOP-590]: https://quintoandar.atlassian.net/browse/MLOP-590

Release 1.1.1

---

tests/unit/butterfree/transform/features/test_feature.py

[BUG] Fix style

---

.github/workflows/staging.yml
.github/workflows/test.yml

We are updating our workflow to create development packages for testing and to mitigate potential problems.
- Github Actions Pipelines

[MLOP-634] Butterfree dev workflow, set triggers for branches staging and master

---

.github/workflows/staging.yml

The current configuration of the pipeline did not work because it does not change the name of the package to add to PyPI.
- Staging Pipeline

[BUG] Fix Staging GithubActions Pipeline

---

.github/workflows/staging.yml
Makefile

The current configuration of the pipeline did not work because it does not send the package to PyPI.
- Staging Pipeline
- Makefile

[BUG] Change version on setup.py to PyPI

---

CHANGELOG.md
setup.py

Let's create a dev package to test the change from from_ms in TimestampFeature.
- Version Dev
- Changelog Unreleased

Create a dev package

---

README.md
WORKFLOW.md

Update documentation to inform publicly the dev workflow.
- Workflow.md

[MLOP-633] Butterfree dev workflow, update documentation

---

butterfree/migrations/__init__.py
butterfree/migrations/cassandra_migration.py
butterfree/migrations/metastore_migration.py
butterfree/migrations/migration.py

The goal of this PR is to establish an abstract base class for the Migration entity.
Added an abstract base class and two other migration classes for our current databases (Cassandra) and object storage (S3).
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._

[MLOP-636] Create migration classes

---

butterfree/transform/aggregated_feature_set.py
setup.py
tests/unit/butterfree/transform/conftest.py
tests/unit/butterfree/transform/test_aggregated_feature_set.py

This is a fix to a typo.
Fixed the typo.
Unit test.

Fix Slide Duration Typo

---

butterfree/configs/db/metastore_config.py
butterfree/load/sink.py
butterfree/load/writers/historical_feature_store_writer.py
butterfree/load/writers/online_feature_store_writer.py
setup.py
tests/integration/butterfree/load/test_sink.py
tests/integration/butterfree/pipelines/test_feature_set_pipeline.py
tests/unit/butterfree/load/test_sink.py
tests/unit/butterfree/load/writers/test_historical_feature_store_writer.py
tests/unit/butterfree/load/writers/test_online_feature_store_writer.py

It was necessary to fix some issues.
Fixed validation step and spark client translate method.
Unit and integration tests.
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._

Fix Validation Step

---

butterfree/_cli/migrate.py
requirements.txt
setup.py

We decided to change the tool used to send logs for S3.
- Migrate
- 
- We tested in [Databricks notebook](https://dbc-931ee6e0-6803.cloud.databricks.com/?o=4531937035440038#notebook/101864758484317/command/101864758484338)

Change solution for tracking logs

---

butterfree/clients/spark_client.py
setup.py
tests/unit/butterfree/clients/test_spark_client.py

Resolve to fix with params of read method.
- SparkClient
- Unit and integration tests

[BUG] Fix SparkClient read method

---

butterfree/_cli/migrate.py
butterfree/clients/abstract_client.py
butterfree/clients/cassandra_client.py
butterfree/clients/spark_client.py
butterfree/load/writers/online_feature_store_writer.py
butterfree/migrations/database_migration/database_migration.py
setup.py
tests/unit/butterfree/_cli/test_migrate.py

We will focus on developing migrations for Cassandra and in the future, we will return with developing migrations for Metastore.
- DatabaseMigration
- Unit tests

Remove metastore migrate

---

butterfree/_cli/migrate.py
setup.py

We need to fix the condition for db-config.
- Migrate

Fix db-config condition

---

butterfree/_cli/migrate.py

Improve message for local logging file in butterfree cli.
- Migrate
- Unit test
- Local test

[MLOP-727] Improve logging messages

---

CHANGELOG.md
setup.py

We need to do a new release, but the branch staging is outdated.
- Update staging files.

Update files to staging

---

CHANGELOG.md
setup.py

Reverts quintoandar/butterfree#336

Revert "Update files to staging"

---

CHANGELOG.md
setup.py

pre-release 1.2.2.dev0

---

CHANGELOG.md
setup.py

pre-release 1.2.3

---

Makefile
requirements.dev.txt
setup.cfg

Sphinx 3.x is not compatible with Python 3.9
- Update Sphinx and its dependencies

fix: sphinx version

---

CHANGELOG.md
Makefile
setup.py

Publish pipeline is not working

Hotfix package

---

butterfree/configs/db/cassandra_config.py

Add Timestamp NTZ to Cassandra Type Map

fix: new type

---

butterfree/_cli/migrate.py
requirements.txt

Migrate script is failing.
Bump boto.

fix(MLOP-2450): version, format

---

butterfree/transform/aggregated_feature_set.py

It may affect windowed operations.

fix: move incremental filter
